AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Speakeasy

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'Content-type, Accept'"
      AllowOrigin: "'*'"

Resources:
  SynthesizeSpeechFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: SpeakeasyFunctions
      Handler: com.dbarishic.speakeasy.SynthesizeSpeechFunction::handleRequest
      Runtime: java8
      MemorySize: 192
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          BUCKET_NAME: speakeasy-mp3
      Events:
        Speakeasy:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          BinaryMediaTypes:
            - audio~1mpeg
          Properties:
            Path: /synthesize-voice
            Method: post

      Role: !GetAtt [ SynthesizeSpeechFunctionRole, Arn ]

  SynthesizeSpeechFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AmazonPollyFullAccess

  ListAvailableLanguagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: SpeakeasyFunctions
      Handler: com.dbarishic.speakeasy.ListAvailableLanguagesFunction::handleRequest
      Runtime: java8
      MemorySize: 192
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        Speakeasy:
          Type: Api
          Properties:
            Path: /get-languages
            Method: get
      Role: !GetAtt [ ListAvailableLanguagesFunctionRole, Arn ]

  ListAvailableLanguagesFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
        - arn:aws:iam::aws:policy/AmazonPollyFullAccess


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SpeakeasyApi:
    Description: "API Gateway endpoint URL for Prod stage for Speakeasy functions"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/synthesize-voice/"
  SynthesizeSpeechFunction:
    Description: "SynthesizeSpeechFunction Lambda Function ARN"
    Value: !GetAtt SynthesizeSpeechFunction.Arn
  SynthesizeSpeechFunctionIamRole:
    Description: "IAM Execution Role created for SynthesizeSpeechFunction function"
    Value: !GetAtt SynthesizeSpeechFunctionRole.Arn
  ListAvailableLanguagesFunction:
    Description: "ListAvailableLanguagesFunction Lambda Function ARN"
    Value: !GetAtt ListAvailableLanguagesFunction.Arn
  ListAvailableLanguagesFunctionRole:
    Description: "IAM Execution Role created for ListAvailableLanguagesFunction"
    Value: !GetAtt ListAvailableLanguagesFunctionRole.Arn
